AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false
